# Generated by Django 6.0.6 on 2026-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default=0, max_length=20),
        ),
    ]
